### PR TITLE
Allow data dir to be independent of install dir

### PR DESCRIPTION
**Pull request by jj-umn**
I am suggesting a few changes that I think may be useful for installing
eggnog-mapper via bioconda and using it in a galaxy installation.  This
allows the data dir to be independent of the installation directory.
Also allows a path for the diamond db.

### CODE REVIEW

**Comment by jhcepas** [comment]
looks nice! thanks @jj-umn 
I will review and integrate as soon as posible.

**Comment by jj-umn** [comment]
@jhcepas Thanks.   When making a galaxy tool, we try to have a minuscule amount of data in the tool test-data directory to verify the tool is working.  Being able to specify paths allows use of tiny diamond db or hmm db from that test-data dir.  
I'll also start looking at creating a conda recipe for installing eggnog-mapper to put in:  https://github.com/bioconda/bioconda-recipes

**Comment by jhcepas** [comment]
that sounds great. Would you be willing to share that testing code and data? 
Unittests are still in the TODO list here...

**Comment by jj-umn** [comment]
@jhcepas  If I can figure out some minimal testing data, I'll be happy to share.

**Pull request merged**
